### ISSUE TITLE
Functionality Test Suite

### ISSUE THREAD

**Issue by HaoZeke** [prestsoftware/prest#5]
**Acceptance Blocker (https://github.com/openjournals/joss-reviews/issues/1015)**

# Details
As per the JOSS review guidelines, the tests to be included are to be classified as:

> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

    Good: An automated test suite hooked up to an external service such as Travis-CI or similar
    OK: Documented manual steps that can be followed to check the expected functionality of the software (e.g. a sample input file to assert behaviour)
    Bad (not acceptable): No way for you the reviewer to check whether the software works

At the moment, in-spite of very well documented functionality and some example inputs, I cannot seem to find any overall tests which showcase high level functionality in a deterministic manner.

This is somewhat related to the issue of examples, however after reading the documentation I determined that the sample inputs and documentation provide appropriate example usage.

**Comment by ziman** [comment]
The [test suite documented in the README](https://github.com/prestsoftware/prest#testing) includes an [integration test](https://github.com/prestsoftware/prest/blob/master/gui/test/integration_test.py), which runs the whole pipeline including the Rust core on the examples provided in the documentation and compares the outputs with the expected values. I think that this test suite covers the main subset of the high-level functionality of the software reasonably but perhaps my reading of the guidelines is incorrect.

What other tests would you prefer to see? Or perhaps we should document the tests better?

**Comment by HaoZeke** [comment]
Thanks for highlighting that! I think some slight changes to the documentation (the generated html files) which could like to the integration tests would be a good idea.

Having gone through the code and the test itself I am closing this here, however please consider updating the `html` docs.

**Comment by HaoZeke** [comment]
In particular, I was wondering if perhaps the CLI tool mentioned in the paper (to model estimation for testing and benchmarking) would be a part of this repo eventually.

**Comment by ziman** [comment]
The fact that you could not find the test indicates that it indeed needs to be documented properly.

However, the HTML documentation is intended mainly for end users and I feel like developer information, such as test descriptions, would be better placed elsewhere, such as CONTRIBUTING.md or perhaps README.md.

As for [the CLI tool](https://github.com/prestsoftware/prest/blob/master/gui/cli.py), it is indeed silently included in the repository. We do not document it as supported functionality because we still need to find a way to make model selection and export variant selection more ergonomic — at the moment you are required to select them by their description string, exactly character by character.

**Comment by HaoZeke** [comment]
That is excellent 😁 (the silent cli inclusion)

I look forward to seeing this project grow!

Thanks for the new changes clarifying the tests
